---
- name: Copying token to worker nodes
  copy: src=/home/{{ ansible_user }}/{{ token_file }} dest=/home/{{ ansible_user }}/join_token

- name: Joining worker nodes with kubernetes master
  shell: |
   kubeadm reset -f
   cat /home/{{ ansible_user }}/join_token | tail -2 > out.sh
   sh out.sh

