---
- name: Disabling Swap on all nodes
  shell: /sbin/swapoff -a

- name: Commenting Swap entries in /etc/fstab
  replace:
   path: /etc/fstab
   regexp: '(.*swap*)'
   replace: '#\1'

- name: Creating a repository file for Kubernetes
  file:
   path: /etc/yum.repos.d/kubernetes.repo
   state: touch

- name: Adding repository details in Kubernetes repo file.
  blockinfile:
   path: /etc/yum.repos.d/kubernetes.repo
   block: |
    [kubernetes]
    name=Kubernetes
    baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled=1
    gpgcheck=1
    repo_gpgcheck=1
    gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
    https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Installing Docker and firewalld
  shell: |
   yum install firewalld -y
   yum install -y yum-utils device-mapper-persistent-data lvm2
   yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
   yum install docker-ce -y

- name: Installing required packages
  yum:
   name: "{{ item }}"
   state: present
  with_items: "{{ packages }}"

- name: Starting and Enabling the required services
  service:
   name: "{{ item }}"
   state: started
   enabled: yes
  with_items: "{{ services }}"

- name: Enable firewalld service
  systemd:
    state: restarted
    daemon_reload: yes
    name: firewalld
    enabled: yes

- name: Open ports
  firewalld:
    port: "{{item}}"
    permanent: true
    state: enabled
  with_items:
    - 6443/tcp
    - 5443/tcp
    - 2379-2380/tcp
    - 10250/tcp
    - 10251/tcp
    - 10252/tcp
    - 10053/tcp
    - 10053/udp
    - 10255/tcp
    - 30000-32767/tcp
    - 8082/tcp
    - 8472/udp
    - 8285/udp
    - 9898/tcp
    - 9100/tcp
    - 443/tcp
    - 53/tcp
    - 53/udp
    - 4194/tcp
    - 10254/tcp

# Port forwarding requires masquerading - https://www.certdepot.net/rhel7-get-started-firewalld/
# Network Zones - https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/sec-using_firewalls#sec-Understanding_Network_Zones
- name: Enable IP masquerading
  shell: "firewall-cmd --permanent --zone={{ network_zone }} --add-masquerade"

- name: Reload firewalld
  shell: firewall-cmd --reload

- name: Enabling Bridge Firewall Rule
  shell: "echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables"

