---
- name: Disabling Swap on all nodes
  shell: /sbin/swapoff -a

- name: Commenting Swap entries in /etc/fstab
  replace:
   path: /etc/fstab
   regexp: '(.*swap*)'
   replace: '#\1'

- name: Remove old Docker
  yum: name={{ item }} state=absent
  loop:
   - docker
   - docker-client
   - docker-client-latest
   - docker-common
   - docker-latest
   - docker-latest-logrotate
   - docker-logrotate
   - docker-engine

- name: add repo
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Add kubernetes repo
  yum_repository:
    name: kubernetes
    description: Kubernetes repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgcheck: no
    sslverify: no
    enabled: true

- name: update 
  yum: name=* state=latest

- name: Centos Docker CE
  yum: name={{ item }} state=latest
  loop:
   - "{{ packages }}"


- name: Start docker service
  shell: systemctl daemon-reload && systemctl enable docker && systemctl restart docker

- name: adding existing user "{{ ansible_user }}" to group sudo
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: yes

- name: Add kubernetes repo
  yum_repository:
    name: kubernetes
    description: Kubernetes repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgcheck: no
    sslverify: no
    enabled: true



- name: Installing required packages
  yum:
   name: "{{ item }}"
   state: present
  loop: "{{ packages }}"

- name: Starting and Enabling the required services
  service:
   name: "{{ item }}"
   state: started
   enabled: yes
  loop: "{{ services }}"

- name: Open ports
  firewalld:
    port: "{{item}}"
    permanent: true
    state: enabled
  loop:
    - 6443/tcp
    - 5443/tcp
    - 2379-2380/tcp
    - 10250/tcp
    - 10251/tcp
    - 10252/tcp
    - 10053/tcp
    - 10053/udp
    - 10255/tcp
    - 30000-32767/tcp
    - 8082/tcp
    - 8472/udp
    - 8285/udp
    - 9898/tcp
    - 9100/tcp
    - 443/tcp
    - 53/tcp
    - 53/udp
    - 4194/tcp
    - 10254/tcp

# Port forwarding requires masquerading - https://www.certdepot.net/rhel7-get-started-firewalld/
# Network Zones - https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/sec-using_firewalls#sec-Understanding_Network_Zones
- name: Enable IP masquerading
  shell: "firewall-cmd --permanent --zone={{ network_zone }} --add-masquerade"

- name: Reload firewalld
  shell: firewall-cmd --reload

- name: Enabling Bridge Firewall Rule
  shell: "echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables"

