---
- name: Pulling images required for setting up a Kubernetes cluster
  shell: kubeadm config images pull

- name: Resetting kubeadm
  shell: kubeadm reset -f
  register: output

- name: Initializing Kubernetes cluster
  shell: kubeadm init --apiserver-advertise-address {{ad_addr}} --pod-network-cidr={{cidr_v}}
  register: output

- name: Storing Logs and Generated token for future purpose.
  local_action: copy content={{ output.stdout }} dest=/home/{{ ansible_user }}/{{ token_file }}
  ignore_errors: true

- name: Copying required files
  shell: |
   mkdir -p /home/{{ansible_user}}/.kube
   sudo cp -f /etc/kubernetes/admin.conf /home/{{ansible_user}}/.kube/config
   sudo cp -f /etc/kubernetes/admin.conf /root/.kube/config
   sudo chown {{ansible_user}}:{{ansible_user}} /home/{{ansible_user}}/.kube/config

- name: Install Network Add-on
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

