---
- hosts: all
  become: true
  tasks:
  - name: Disabling Swap on all nodes
    shell: /sbin/swapoff -a

  - name: Commenting Swap entries in /etc/fstab
    replace:
     path: /etc/fstab
     regexp: '(.*swap*)'
     replace: '#\1'

  
